// Shell completion generation (Issue #777). The script is generated from the
// live flag registry (commander's resolved options), never a hand-maintained
// list, so it cannot drift from --help. Bash first; zsh/fish can extend the
// same registry later. The script is inert until the user sources it, and it
// enumerates only flags already visible in --help — no new privilege.

export interface CompletionFlag {
  // The long form, e.g. "--workspace".
  long: string;
  // The short form when one exists, e.g. "-p".
  short?: string;
  // The option description (unused by the script today; carried so richer
  // shells can surface it later without a registry change).
  description?: string;
}

// Sanitize the command name into a safe bash completion-function name
// (letters/digits/underscores; anything else collapses to one underscore).
export function completionFunctionName(commandName: string): string {
  return `_${commandName.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "")}`;
}

// Generate a bash completion script for the command's flags. Flags are
// completed when the current word starts with "-"; anything else falls back
// to default (filename) completion. Pure: registry in, script text out.
export function generateBashCompletion(
  commandName: string,
  flags: readonly CompletionFlag[],
): string {
  const fn = completionFunctionName(commandName);
  const words = flags
    .flatMap((flag) => (flag.short ? [flag.long, flag.short] : [flag.long]))
    .sort()
    .join(" ");
  return [
    `# bash completion for ${commandName} — generated by ${commandName} --setup-completions; do not edit`,
    `${fn}() {`,
    `  local cur`,
    `  cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `  local flags="${words}"`,
    `  if [[ "\${cur}" == -* ]]; then`,
    `    COMPREPLY=( $(compgen -W "\${flags}" -- "\${cur}") )`,
    `    return 0`,
    `  fi`,
    `  COMPREPLY=( $(compgen -f -- "\${cur}") )`,
    `  return 0`,
    `}`,
    `complete -o default -F ${fn} ${commandName}`,
  ].join("\n");
}
