// Shell completion generation (Issues #777, #779). The script is generated
// from the live flag registry (commander's resolved options), never a
// hand-maintained list, so it cannot drift from --help. Bash and zsh today;
// fish can extend the same registry later. The script is inert until the
// user sources it, and it enumerates only flags already visible in --help —
// no new privilege.

export interface CompletionFlag {
  // The long form, e.g. "--workspace".
  long: string;
  // The short form when one exists, e.g. "-p".
  short?: string;
  // The option description (unused by the script today; carried so richer
  // shells can surface it later without a registry change).
  description?: string;
}

// Sanitize the command name into a safe bash completion-function name
// (letters/digits/underscores; anything else collapses to one underscore).
export function completionFunctionName(commandName: string): string {
  return `_${commandName.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "")}`;
}

// Generate a bash completion script for the command's flags. Flags are
// completed when the current word starts with "-"; anything else falls back
// to default (filename) completion. Pure: registry in, script text out.
export function generateBashCompletion(
  commandName: string,
  flags: readonly CompletionFlag[],
): string {
  const fn = completionFunctionName(commandName);
  const words = flags
    .flatMap((flag) => (flag.short ? [flag.long, flag.short] : [flag.long]))
    .sort()
    .join(" ");
  return [
    `# bash completion for ${commandName} — generated by ${commandName} --setup-completions; do not edit`,
    `${fn}() {`,
    `  local cur`,
    `  cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `  local flags="${words}"`,
    `  if [[ "\${cur}" == -* ]]; then`,
    `    COMPREPLY=( $(compgen -W "\${flags}" -- "\${cur}") )`,
    `    return 0`,
    `  fi`,
    `  COMPREPLY=( $(compgen -f -- "\${cur}") )`,
    `  return 0`,
    `}`,
    `complete -o default -F ${fn} ${commandName}`,
  ].join("\n");
}

// Escape a flag description for a zsh `_describe` spec: colons separate
// spec fields, so they (and the backslashes that escape them) must be
// escaped; brackets are literal inside a describe spec.
export function zshDescribeText(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/:/g, "\\:");
}

// Generate a zsh completion script for the command's flags (Issue #779).
// Flag candidates carry their descriptions through `_describe`; non-dash
// input falls back to default completion. Requires the user's standard
// compinit setup (the normal zsh completion environment). Pure: registry in,
// script text out.
export function generateZshCompletion(
  commandName: string,
  flags: readonly CompletionFlag[],
): string {
  const fn = completionFunctionName(commandName);
  const specs = flags
    .map((flag) => {
      const spec = flag.description
        ? `${flag.long}:${zshDescribeText(flag.description)}`
        : flag.long;
      return `    '${spec.replace(/'/g, "'\\''")}'`;
    })
    .sort()
    .join("\n");
  return [
    `#compdef ${commandName}`,
    `# zsh completion for ${commandName} — generated by ${commandName} --setup-completions; do not edit`,
    ``,
    `${fn}() {`,
    `  if [[ $words[$CURRENT] == -* ]]; then`,
    `    local -a flags`,
    `    flags=(`,
    specs,
    `    )`,
    `    _describe 'flag' flags`,
    `    return 0`,
    `  fi`,
    `  _default`,
    `  return 0`,
    `}`,
    ``,
    `compdef ${fn} ${commandName}`,
  ].join("\n");
}
